name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        path: .

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Grant execute permissions to Maven wrapper
      run: chmod +x mvnw

    - name: Build and Test
      run: |
        ./mvnw clean install
    
    - name: Debug Information
      run: |
        pwd
        ls -al

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to Production
      run: |
        # Add deployment scripts/commands here
        echo "Deploying to production..."